import type { Provider } from './types';

export const amlProviders: Provider[] = [
  {
    id: 'shieldpay',
    name: 'ShieldPay',
    logo: 'SP',
    tagline: 'Instant digital AML verification',
    tier: 1,
    price: 24.99,
    turnaround: '< 5 minutes',
    rating: 4.8,
    reviews: 2341,
    features: [
      'Biometric ID verification',
      'PEP & sanctions screening',
      'Portable AML certificate',
      'FCA-authorised payments',
    ],
    highlight: 'Recommended',
    regulated: 'FCA Authorised',
  },
  {
    id: 'thirdfort',
    name: 'Thirdfort',
    logo: 'TF',
    tagline: 'Bank-grade identity checks trusted by 1,000+ law firms',
    tier: 1,
    price: 29.99,
    turnaround: '< 10 minutes',
    rating: 4.7,
    reviews: 1876,
    features: [
      'Open banking verification',
      'Source of funds check',
      'DIATF-certified',
      'Multi-jurisdictional support',
    ],
    highlight: 'Top Rated',
    regulated: 'ICO Registered',
  },
  {
    id: 'credas',
    name: 'Credas',
    logo: 'CR',
    tagline: 'AI-powered identity verification for property transactions',
    tier: 2,
    price: 19.99,
    turnaround: '< 15 minutes',
    rating: 4.5,
    reviews: 1203,
    features: [
      'Document OCR scanning',
      'Liveness detection',
      'Address verification',
      'Reusable ID profile',
    ],
    highlight: 'Best Value',
    regulated: 'DIATF Certified',
  },
  {
    id: 'verify365',
    name: 'Verify 365',
    logo: 'V3',
    tagline: 'Complete AML compliance suite for conveyancing',
    tier: 2,
    turnaround: '< 30 minutes',
    rating: 4.3,
    reviews: 892,
    features: [
      'ID document check',
      'Watchlist screening',
      'Enhanced due diligence',
      'PDF certificate export',
    ],
    highlight: 'Budget',
    regulated: 'FCA Authorised',
  },
];

export const searchProviders: Provider[] = [
  {
    id: 'searchflow',
    name: 'SearchFlow',
    logo: 'SF',
    tagline: 'Digital-first property searches with real-time tracking',
    tier: 1,
    price: 289.0,
    turnaround: '3–5 working days',
    rating: 4.6,
    reviews: 1567,
    features: [
      'Full search bundle included',
      'Real-time status tracking',
      'Digital delivery',
      'Automated council liaison',
    ],
    highlight: 'Recommended',
    regulated: 'CoPSO Member',
  },
  {
    id: 'landmark',
    name: 'Landmark Information',
    logo: 'LM',
    tagline: 'The UK\'s largest property data provider',
    tier: 1,
    price: 310.0,
    turnaround: '2–4 working days',
    rating: 4.7,
    reviews: 2104,
    features: [
      'Comprehensive environmental data',
      'Mining report included',
      'Chancel repair liability',
      'Insurance-backed results',
    ],
    highlight: 'Fastest',
    regulated: 'CoPSO Member',
  },
  {
    id: 'tmgroup',
    name: 'tmGroup',
    logo: 'TM',
    tagline: 'End-to-end search management for conveyancers',
    tier: 1,
    price: 275.0,
    turnaround: '3–7 working days',
    rating: 4.5,
    reviews: 1890,
    features: [
      'Integrated with 350+ councils',
      'Bulk ordering discount',
      'Regulated search insurance',
      'API integration ready',
    ],
    highlight: 'Best Value',
    regulated: 'CoPSO Member',
  },
  {
    id: 'council-direct',
    name: 'Direct from Council',
    logo: 'DC',
    tagline: 'Official local authority searches at source',
    tier: 2,
    price: 195.0,
    turnaround: '5–20 working days',
    rating: 4.2,
    reviews: 634,
    features: [
      'Official LA results',
      'No intermediary markup',
      'Con29R + Con29O available',
      'LLC1 included',
    ],
    regulated: 'Local Authority',
  },
];

export const conveyancerProviders: Provider[] = [
  {
    id: 'richardsons',
    name: 'Richardsons Law',
    logo: 'RL',
    tagline: 'Specialist residential conveyancing in Bedfordshire',
    tier: 1,
    price: 995.0,
    turnaround: '8–12 weeks avg',
    rating: 4.8,
    reviews: 342,
    features: [
      'Fixed fee — no hidden costs',
      'Dedicated case handler',
      'Online portal access',
      'CQS accredited',
    ],
    highlight: 'Local',
    regulated: 'SRA Regulated',
    location: 'Bedford',
  },
  {
    id: 'adamson',
    name: 'Adamson Law',
    logo: 'AL',
    tagline: 'Modern conveyancing with a personal touch',
    tier: 1,
    price: 1100.0,
    turnaround: '8–10 weeks avg',
    rating: 4.9,
    reviews: 218,
    features: [
      'No completion no fee',
      'Same-day responses',
      'Digital signing via tmSign',
      'Transparent pricing',
    ],
    highlight: 'Top Rated',
    regulated: 'SRA Regulated',
    location: 'Sandy',
  },
  {
    id: 'woodfines',
    name: 'Woodfines Solicitors',
    logo: 'WF',
    tagline: 'Established 1895 — trusted across Bedfordshire & beyond',
    tier: 2,
    price: 1250.0,
    turnaround: '10–14 weeks avg',
    rating: 4.6,
    reviews: 567,
    features: [
      'Full-service firm',
      'Complex transactions welcome',
      'Leasehold specialists',
      'Multi-branch coverage',
    ],
    highlight: 'Local Expert',
    regulated: 'SRA Regulated',
    location: 'Bedford',
  },
  {
    id: 'quickconvey',
    name: 'Quick Convey',
    logo: 'QC',
    tagline: 'Fast, affordable nationwide online conveyancing',
    tier: 1,
    price: 750.0,
    turnaround: '6–10 weeks avg',
    rating: 4.4,
    reviews: 1203,
    features: [
      'Fully online process',
      '24/7 case tracking',
      'No completion no fee',
      'Volume-tested systems',
    ],
    highlight: 'Best Value',
    regulated: 'CLC Licensed',
    location: 'Nationwide',
  },
];

export const surveyProviders: Provider[] = [
  {
    // Live referral partner (Landmark Information Group). Selecting Optimus
    // fires a real email referral via the optimus-survey-referral edge
    // function — see SurveyPanel. Price is the lowest Level 2 band (≤£100k,
    // inc VAT) from Optimus's Jun 2026 rate card, minus the £135 referral
    // fee Graham Stanbridge waived for PropXchain buyers (email 2026-06-25).
    // Bands rise with property value; Optimus quote the exact figure after
    // contacting the customer.
    id: 'optimus',
    name: 'Optimus Surveys',
    logo: 'OP',
    tagline: 'Landmark Group\'s national panel of RICS surveyors',
    tier: 1,
    price: 468.0,
    turnaround: 'Quote within 1 working day',
    rating: 4.6,
    reviews: 412,
    features: [
      'All RICS survey levels',
      'Personal quote before you commit',
      'Nationwide surveyor panel',
      'Backed by Landmark Information Group',
    ],
    highlight: 'Recommended',
    regulated: 'RICS',
  },
  // Other surveyors removed 2026-07-24 while Optimus is the sole live
  // referral partner — restore from git history if the panel reopens.
];
