/**
 * AP1Form - Guided form for creating an AP1 Application to Change the Register
 * Auto-populates from transaction data, conveyancer fills remaining fields
 * Generates PDF via jsPDF and registers hash on-chain
 */

import React, { useState, useMemo } from 'react';
import jsPDF from 'jspdf';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import { icpService } from '@/services/icp.service';
import { logger } from '@/utils/logger';

interface AP1FormProps {
  isOpen: boolean;
  onClose: () => void;
  onComplete: (docId: number) => void;
  transaction: {
    id: string;
    propertyAddress: string;
    amount: number;
    buyer: string;
    seller: string;
  };
}

type FormStep = 'details' | 'review';

interface AP1Fields {
  titleNumber: string;
  applicationType: 'TRANSFER' | 'CHARGE' | 'OTHER';
  priority: 'STANDARD' | 'EXPEDITED';
  executionDate: string;
  solicitorReference: string;
  applicantAddress: string;
}

const AP1Form: React.FC<AP1FormProps> = ({
  isOpen,
  onClose,
  onComplete,
  transaction,
}) => {
  const [step, setStep] = useState<FormStep>('details');
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [fields, setFields] = useState<AP1Fields>({
    titleNumber: '',
    applicationType: 'TRANSFER',
    priority: 'STANDARD',
    executionDate: new Date().toISOString().split('T')[0],
    solicitorReference: '',
    applicantAddress: '',
  });

  const updateField = <K extends keyof AP1Fields>(key: K, value: AP1Fields[K]): void => {
    setFields((prev) => ({ ...prev, [key]: value }));
  };

  const isDetailsValid = useMemo((): boolean => {
    return fields.titleNumber.trim().length > 0 && fields.executionDate.length > 0;
  }, [fields.titleNumber, fields.executionDate]);

  const generatePDF = (): Blob => {
    const doc = new jsPDF();
    const pw = doc.internal.pageSize.getWidth();
    let y = 20;

    // Header
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 51, 102);
    doc.text('FORM AP1', pw / 2, y, { align: 'center' });
    y += 8;
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(80);
    doc.text('Application to change the register', pw / 2, y, { align: 'center' });

    y += 15;
    doc.setDrawColor(0, 51, 102);
    doc.setLineWidth(0.5);
    doc.line(20, y, pw - 20, y);
    y += 10;

    const addField = (label: string, value: string): void => {
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0);
      doc.text(label, 25, y);
      doc.setFont('helvetica', 'normal');
      const lines = doc.splitTextToSize(value, pw - 100);
      doc.text(lines, 80, y);
      y += Math.max(8, lines.length * 6);
    };

    const appTypeLabels: Record<string, string> = {
      TRANSFER: 'Transfer of whole title',
      CHARGE: 'Charge',
      OTHER: 'Other',
    };

    addField('1. Application:', appTypeLabels[fields.applicationType]);
    addField('   Priority:', fields.priority === 'EXPEDITED' ? 'Expedited' : 'Standard');
    addField('2. Title Number:', fields.titleNumber);
    addField('3. Property:', transaction.propertyAddress);
    addField('4. Applicant:', transaction.buyer);
    if (fields.applicantAddress) addField('   Address:', fields.applicantAddress);
    if (fields.solicitorReference) addField('   Reference:', fields.solicitorReference);
    addField('5. Transferor:', transaction.seller);
    addField('6. Transferee:', transaction.buyer);
    addField('7. Consideration:', `£${transaction.amount.toLocaleString()}`);
    addField('8. Execution Date:', new Date(fields.executionDate).toLocaleDateString('en-GB'));

    y += 10;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 51, 102);
    doc.text('SUPPORTING DOCUMENTS', 25, y);
    y += 8;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(0);
    const supportingDocs = [
      'TR1 - Transfer of whole of registered title',
      'ID1 - Identity verification for transferor',
      'ID1 - Identity verification for transferee',
    ];
    supportingDocs.forEach((d) => {
      doc.text(`  - ${d}`, 25, y);
      y += 7;
    });

    y += 10;
    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.text('Generated by PropXchain - Blockchain Property Conveyancing', pw / 2, y, { align: 'center' });
    doc.text(`Transaction ID: ${transaction.id}`, pw / 2, y + 5, { align: 'center' });

    return doc.output('blob');
  };

  const handleSubmit = async (): Promise<void> => {
    setSubmitting(true);
    setError(null);
    try {
      const pdfBlob = generatePDF();
      const pdfFile = new File([pdfBlob], `AP1_${fields.titleNumber || 'application'}.pdf`, {
        type: 'application/pdf',
      });

      const result = await icpService.registerDocumentProof(
        pdfFile,
        0,
        'ap1_application',
        'onchain',
        transaction.id,
      );

      const localDocs = JSON.parse(localStorage.getItem(`conveyancer_docs_${transaction.id}`) || '[]');
      localDocs.push({
        storageDocId: result.storageDocumentId,
        docType: 'ap1_application',
        fileName: pdfFile.name,
        hash: result.documentHash,
        createdAt: new Date().toISOString(),
      });
      localStorage.setItem(`conveyancer_docs_${transaction.id}`, JSON.stringify(localDocs));

      const url = URL.createObjectURL(pdfBlob);
      const a = document.createElement('a');
      a.href = url;
      a.download = pdfFile.name;
      a.click();
      URL.revokeObjectURL(url);

      onComplete(result.storageDocumentId);
    } catch (err) {
      const msg = err instanceof Error ? err.message : 'Failed to register AP1';
      logger.error('AP1 submission failed:', err);
      setError(msg);
    } finally {
      setSubmitting(false);
    }
  };

  const inputClass = 'w-full h-10 px-3 text-sm border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-900 text-gray-900 dark:text-white focus:ring-2 focus:ring-blue-500 focus:border-transparent';
  const labelClass = 'block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1';

  return (
    <Dialog open={isOpen} onOpenChange={(open) => { if (!open) onClose(); }}>
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <DialogTitle>Generate AP1 Application</DialogTitle>
          <DialogDescription>
            Step {step === 'details' ? '1/2' : '2/2'}
            {' — '}
            {step === 'details' ? 'Application Details' : 'Review & Submit'}
          </DialogDescription>
        </DialogHeader>

        <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg px-3 py-2">
          <p className="text-xs text-blue-700 dark:text-blue-300">
            Property: <strong>{transaction.propertyAddress}</strong> |
            Price: <strong>£{transaction.amount.toLocaleString()}</strong>
          </p>
        </div>

        {/* Step 1: Details */}
        {step === 'details' && (
          <div className="space-y-3">
            <div>
              <label className={labelClass}>Title Number *</label>
              <input
                type="text"
                value={fields.titleNumber}
                onChange={(e) => updateField('titleNumber', e.target.value.toUpperCase())}
                className={inputClass}
                placeholder="e.g., NGL123456"
              />
            </div>
            <div>
              <label className={labelClass}>Application Type</label>
              <select
                value={fields.applicationType}
                onChange={(e) => updateField('applicationType', e.target.value as AP1Fields['applicationType'])}
                className={inputClass}
              >
                <option value="TRANSFER">Transfer of whole title</option>
                <option value="CHARGE">Charge</option>
                <option value="OTHER">Other</option>
              </select>
            </div>
            <div>
              <label className={labelClass}>Priority</label>
              <select
                value={fields.priority}
                onChange={(e) => updateField('priority', e.target.value as AP1Fields['priority'])}
                className={inputClass}
              >
                <option value="STANDARD">Standard</option>
                <option value="EXPEDITED">Expedited</option>
              </select>
            </div>
            <div>
              <label className={labelClass}>Execution Date *</label>
              <input
                type="date"
                value={fields.executionDate}
                onChange={(e) => updateField('executionDate', e.target.value)}
                className={inputClass}
              />
            </div>
            <div>
              <label className={labelClass}>Solicitor Reference</label>
              <input
                type="text"
                value={fields.solicitorReference}
                onChange={(e) => updateField('solicitorReference', e.target.value)}
                className={inputClass}
                placeholder="Your file reference"
              />
            </div>
            <div>
              <label className={labelClass}>Applicant Address</label>
              <input
                type="text"
                value={fields.applicantAddress}
                onChange={(e) => updateField('applicantAddress', e.target.value)}
                className={inputClass}
                placeholder="Buyer's correspondence address"
              />
            </div>
            <button
              onClick={() => setStep('review')}
              disabled={!isDetailsValid}
              className="w-full h-10 bg-green-600 hover:bg-green-700 text-white text-sm font-semibold rounded-lg disabled:opacity-40 transition-colors"
            >
              Next: Review
            </button>
          </div>
        )}

        {/* Step 2: Review */}
        {step === 'review' && (
          <div className="space-y-3">
            <div className="bg-gray-50 dark:bg-gray-900 rounded-lg p-4 space-y-2 text-sm">
              <div className="flex justify-between">
                <span className="text-gray-500">Title Number</span>
                <span className="font-medium text-gray-900 dark:text-white">{fields.titleNumber}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-500">Application</span>
                <span className="font-medium text-gray-900 dark:text-white capitalize">
                  {fields.applicationType.toLowerCase()}
                </span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-500">Priority</span>
                <span className="font-medium text-gray-900 dark:text-white capitalize">
                  {fields.priority.toLowerCase()}
                </span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-500">Property</span>
                <span className="font-medium text-gray-900 dark:text-white text-right max-w-[60%]">{transaction.propertyAddress}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-500">Consideration</span>
                <span className="font-medium text-gray-900 dark:text-white">£{transaction.amount.toLocaleString()}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-500">Execution Date</span>
                <span className="font-medium text-gray-900 dark:text-white">
                  {new Date(fields.executionDate).toLocaleDateString('en-GB')}
                </span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-500">Applicant</span>
                <span className="font-medium text-gray-900 dark:text-white">{transaction.buyer}</span>
              </div>
            </div>

            {error && (
              <div className="bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg px-3 py-2">
                <p className="text-xs text-red-700 dark:text-red-300">{error}</p>
              </div>
            )}

            <div className="flex gap-2">
              <button
                onClick={() => setStep('details')}
                disabled={submitting}
                className="flex-1 h-10 border border-gray-300 dark:border-gray-600 text-gray-700 dark:text-gray-300 text-sm font-medium rounded-lg hover:bg-gray-50 dark:hover:bg-gray-800 transition-colors disabled:opacity-40"
              >
                Back
              </button>
              <button
                onClick={handleSubmit}
                disabled={submitting}
                className="flex-1 h-10 bg-green-600 hover:bg-green-700 text-white text-sm font-semibold rounded-lg disabled:opacity-50 transition-colors"
              >
                {submitting ? 'Generating...' : 'Generate AP1 & Register'}
              </button>
            </div>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
};

export default AP1Form;
